### ISSUE TITLE
Uncaught Error: Cannot find module 'css-element-queries/src/ResizeSensor'

### ISSUE THREAD

**Issue by kevinrenskers** [zalmoxisus/atom-redux-devtools#5]
Whenever I start the package I get the error `Uncaught Error: Cannot find module 'css-element-queries/src/ResizeSensor'`. I'm running 0.3.3.

**Comment by zalmoxisus** [comment]
Thanks for reporting that. 

I can reproduce with the new package. Will investigate in the morning.

**Comment by zalmoxisus** [comment]
@kevinrenskers, something weird was happening with the module dependencies. Atom failed to install them correctly confusing our module with npm's `redux-devtools` as they have the same name. Should be fixed in `0.5.0`.

In case the previous version is crashing Atom (usually after restart), close Atom and open it in safe mode (run form terminal `atom --save`), then update our pacakge.
